// Exports from admin.ts
export {
  AdminDeal,
  AdminDealsResponse,
  AdminDispute,
  AdminDisputesResponse,
  PendingPayout,
  PendingPayoutsResponse,
  GlobalAnalytics,
  LeaderboardEntry,
  getGlobalAnalytics,
  getLeaderboard,
  getAdminDeals,
  getAdminDisputes,
  resolveDispute,
  getPendingPayouts,
  markPayoutPaid,
  DEAL_STATUS_LABELS,
  DISPUTE_STATUS_LABELS,
  DISPUTE_REASON_LABELS,
  ROLE_LABELS,
  ExportFormat,
  exportDeals,
  exportPayouts,
  exportDisputes,
  exportSummary,
} from './admin';

// Exports from analytics.ts (excluding conflicting ones)
export {
  DealStatistics,
  PayoutStatistics,
  TimeSeriesPoint,
  RecentDeal,
  DashboardSummary,
  getDashboardSummary,
  getDealAnalytics,
  getPayoutAnalytics,
  getTimeSeries,
  exportAgentDeals,
  exportAgentPayouts,
  exportAgentSummary,
} from './analytics';

// Exports from auth.ts
export {
  AuthResponse,
  SendSmsResult,
  SendEmailResult,
  AgentRegisterData,
  AgencyRegisterData,
  ConsentInput,
  sendSMS,
  verifySMS,
  sendEmail,
  verifyEmail,
  loginAgency,
  getCurrentUser,
  registerAgent,
  registerAgency,
} from './auth';

// Exports from bank-split.ts
export {
  BankSplitDealType,
  BankSplitStatus,
  PaymentModel,
  RecipientRole,
  RecipientInput,
  Recipient,
  BankSplitDealCreate,
  BankSplitDeal,
  InvoiceResponse,
  StatusTransitionResponse,
  BankSplitDealsListResponse,
  TimelineEvent,
  SendPaymentLinkResponse,
  RegeneratePaymentLinkResponse,
  DisputeCreateRequest,
  DisputeResponse,
  ServiceCompletionRequest,
  ServiceCompletionResponse,
  ServiceCompletionStatus,
  AdjustmentStatus,
  SplitAdjustmentApproval,
  SplitAdjustment,
  SplitAdjustmentCreateRequest,
  SplitAdjustmentCreateResponse,
  SplitAdjustmentsListResponse,
  ClientPassportUpdate,
  ClientPassportResponse,
  ClientPassportStatus,
  createBankSplitDeal,
  getBankSplitDeal,
  getBankSplitDeals,
  submitForSigning,
  markSigned,
  createInvoice,
  releaseDeal,
  cancelBankSplitDeal,
  getDealTimeline,
  sendPaymentLink,
  regeneratePaymentLink,
  createDispute,
  getDispute,
  confirmServiceCompletion,
  getServiceCompletionStatus,
  requestSplitAdjustment,
  getSplitAdjustments,
  approveSplitAdjustment,
  rejectSplitAdjustment,
  updateClientPassport,
  getClientPassportStatus,
  BANK_SPLIT_STATUS_LABELS,
  BANK_SPLIT_STATUS_STYLES,
  RECIPIENT_ROLE_LABELS,
  ADJUSTMENT_STATUS_LABELS,
  ADJUSTMENT_STATUS_STYLES,
} from './bank-split';

// Exports from client.ts
export { apiClient, authClient } from './client';

// Exports from contracts.ts
export {
  ContractStatus,
  ContractType,
  SignatureMethod,
  RequiredSigner,
  ContractListItem,
  Contract,
  ContractsListResponse,
  GenerateContractResponse,
  SignContractResponse,
  CONTRACT_STATUS_LABELS,
  CONTRACT_TYPE_LABELS,
  SIGNATURE_METHOD_LABELS,
  getDealContracts,
  getContract,
  generateContract,
  getContractPdfUrl,
  signContract,
  isContractFullySigned,
  canSignContract,
  hasUserSigned,
  isUserRequiredToSign,
  getMissingSigners,
  getSignedSigners,
  getContractStatusStyle,
} from './contracts';

// Exports from deals.ts
export {
  DealType,
  PropertyType,
  PaymentType,
  AdvanceType,
  DealStatus,
  AddressInput,
  DealCreateSimple,
  CommissionCalculateRequest,
  PaymentStep,
  CommissionCalculateResponse,
  Deal,
  DealsListResponse,
  SendForSigningResponse,
  getDeals,
  getAgencyDeals,
  getDeal,
  createDeal,
  updateDeal,
  submitDeal,
  cancelDeal,
  sendForSigning,
  calculateCommission,
  DEAL_TYPE_LABELS,
  PROPERTY_TYPE_LABELS,
  PAYMENT_TYPE_LABELS,
  ADVANCE_TYPE_LABELS,
} from './deals';

// Exports from invitations.ts
export {
  InvitationRole,
  InvitationStatus,
  InvitationCreate,
  InvitationResponse,
  InvitationPublicInfo,
  InvitationActionResponse,
  createInvitation,
  getDealInvitations,
  cancelInvitation,
  getInvitationByToken,
  acceptInvitation,
  declineInvitation,
  resendInvitation,
  INVITATION_ROLE_LABELS,
  INVITATION_STATUS_LABELS,
} from './invitations';

// Exports from organizations.ts
export {
  AgentInfo,
  AgentListResponse,
  Organization,
  getOrganizations,
  getOrganization,
  getAgents,
  addAgentByPhone,
  removeAgent,
} from './organizations';

// Exports from profile.ts
export {
  LegalType,
  OnboardingStatus,
  KYCStatus,
  PaymentProfile,
  PaymentProfileListResponse,
  OnboardingStartRequest,
  OnboardingStartResponse,
  OnboardingStatusResponse,
  INNValidationResponse,
  BankAutofillResponse,
  CompanyAutofillResponse,
  SettingsProfileResponse,
  AvatarUploadResponse,
  LEGAL_TYPE_LABELS,
  ONBOARDING_STATUS_LABELS,
  KYC_STATUS_LABELS,
  getPaymentProfiles,
  getPaymentProfile,
  startOnboarding,
  getOnboardingStatus,
  validateINN,
  autofillBankByBIK,
  autofillCompanyByINN,
  getSettingsProfile,
  updateSettingsProfile,
  uploadProfileAvatar,
  deleteProfileAvatar,
} from './profile';

// Exports from signing.ts
export {
  SigningInfo,
  RequestOTPResponse,
  VerifySignatureResponse,
  getSigningInfo,
  requestSigningOTP,
  verifyAndSign,
  formatDealType,
  formatPartyRole,
} from './signing';

// Exports from users.ts
export {
  UserSearchResult,
  UserSearchResponse,
  searchUserByPhone,
} from './users';